default:
  controller: Main
  action: home

about-us:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

register:
  controller: Auth
  action: register

dashboard:
  controller: Dashboard
  action: index

installer/step1:
  controller: Backoffice
  action: step1

installer/step2:
  controller: Backoffice
  action: step2

#installer/api:
#  controller: Api
#  action: none

404:
  controller: Main
  action: fourOFour

# STEP 1 : ajotuer la nouvelle route
# STEP 2 : créer la fonction dans le controller désigné dans la route
# STEP 1 : créer un ficher X.form.php dans lequel tu décris les configs