default:
  controller: Main
  action: home

a-propos:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

s-inscrire:
  controller: Auth
  action: register

dashboard:
  controller: Dashboard
  action: index

installer:
  controller: Backoffice
  action: installer

404:
  controller: Main
  action: fourOFour

# STEP 1 : ajotuer la nouvelle route
# STEP 2 : créer la fonction dans le controller désigné dans la route
# STEP 1 : créer un ficher X.form.php dans lequel tu décris les configs