default:
  controller: Main
  action: home

a-propos:
  controller: Main
  action: aboutUs

about-us:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

 

login:
  controller: Auth
  action: login

mail:
  controller: Auth
  action: mail

logout:
  controller: Auth
  action: logout

s-inscrire:
  controller: Auth
  action: register

dashboard:
  controller: Dashboard
  action: index

verify:
  controller: Auth
  action: verify

user_read:
    controller: User
    action: read

user_create:
    path: /user/create
    controller: User
    action: create

user_update:
    path: /user/update/{id}
    controller: User
    action: update

user_delete:
    path: /user/delete/{id}
    controller: User
    action: delete


article_read:
    controller: Article
    action: read
    
article_create:
    controller: Article
    action: create

article_update:
    controller: Article
    action: update

article_delete:
    controller: Article
    action: delete



pages_read:
    controller: Pages
    action: read
    
pages_create:
    controller: Pages
    action: create

pages_update:
    controller: Pages
    action: update

pages_delete:
    controller: Pages
    action: delete

comment_read:
    controller: Comment
    action: read
        
comment_create:
    controller: Comment
    action: create

comment_approve:
  path: /comment/approve/{id}
  controller: Comment
  action: approve

comment_delete:
    path: /comment/delete/{id}
    controller: Comment
    action: delete

comment_show:
    path: /article/show/{id}
    controller: Comment
    action: show    
 

article_show:
    path: /article/show/{id}
    controller: Article
    action: show

# STEP 1 : ajotuer la nouvelle route
# STEP 2 : créer la fonction dans le controller désigné dans la route
# STEP 1 : créer un ficher X.form.php dans lequel tu décris les configs